# templates/app-projects.yaml
{{- range .Values.clusters }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  description: Project for {{ .name }}
  orphanedResources:
    warn: false
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: {{ .server }}
{{- end }}
