# templates/secrets.yaml
{{- range .Values.clusters }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
    {{- if .labels }}
    {{- range $key, $value := .labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
type: Opaque
stringData:
  name: "{{ .name }}"
  server: "{{ .server }}"
  project: "{{ .project | default "" }}"
  config: |
    {{- if eq .clusterType "aws" }}
    {
      "execProviderConfig": {
        "apiVersion": "client.authentication.k8s.io/v1beta1",
        "command": "argocd-k8s-auth",
        "args": [
          "aws",
          "--cluster-name",
          "{{ .awsAuthConfig.clusterName }}",
          "--role-arn",
          "{{ .awsAuthConfig.roleARN }}"
        ],
        "env": {
          "AWS_REGION": "{{ .awsAuthConfig.region }}"
        }
      },
      "tlsClientConfig": {
        "insecure": {{ .tlsClientConfig.insecure }},
        "caData": "{{ .tlsClientConfig.caData }}"
      }        
    }
    {{- else if eq .clusterType "rancher" }}
    {
      "bearerToken": "token-xk7lq:vhn5vzd8rh6jdm6rkbtnkwmbsp5jddslsp8sgm2p5brhcjlmff6jf6",
      "tlsClientConfig": {
        "insecure": false
      }
    }
    {{- else if eq .clusterType "rancher-blue" }}
    {
      "bearerToken": "token-6snsb:whsqkjzjf2hgkmb47chh6clltkct2grxk274q2lh67w2jw57j8fjln",
      "tlsClientConfig": {
        "insecure": false
      }
    }
    {{- else if eq .clusterType "vcluster-expose" }}
    {
      "bearerToken": "{{ .token }}",
      "tlsClientConfig": {
        "insecure": false 
      }
    }
    {{- else if eq .clusterType "gke" }}
    {
      "bearerToken": "{{ .token }}",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "{{ .tlsClientConfig.caData }}"
      }
    }
    {{- else if eq .clusterType "tke" }}
    {
      "bearerToken": "{{ .token }}",
      "tlsClientConfig": {
        "insecure": {{ .tlsClientConfig.insecure }},
        "caData": "{{ .tlsClientConfig.caData }}"
      }
    }
    {{- else if eq .clusterType "kubeconfig" }}
    {
      "tlsClientConfig": {
        "insecure": {{ .tlsClientConfig.insecure | default false }},
        "caData": "{{ .tlsClientConfig.caData }}",
        "certData": "{{ .tlsClientConfig.certData }}",
        "keyData": "{{ .tlsClientConfig.keyData }}"
      }
    }
    {{- end }}
---
{{- end }}
