argocdNamespace: argocd-aws
project: xl-devops-platform-aws-local
repoURL: https://github.com/RiziqStankovic/argocd-migration-sim.git
targetRevision: master
destinationServer: https://kubernetes.default.svc

applications:
  - name: aws-baseline
    path: aws/etc-cluster-config
    namespace: aws-baseline
  - name: aws-cls-log-test
    path: aws/cls-log-test
    namespace: aws-test
  # - name: aws-cls-log-test-aws
  #   path: aws/cls-log-test-aws
  #   namespace: aws-test
