spec:
  destination:
    # server: https://lb.cloudfren.id:443
    server: https://kubernetes.default.svc
    namespace: tencent-prod
  source:
    repoURL: https://github.com/RiziqStankovic/argocd-migration-sim.git
    targetRevision: master

applications:
  - name: tencent-cls-log-test
    namespace: tencent-dev
  # - name: cls-log-test-awstencent
  #   namespace: tencent-nonprod
  #   repoURL: "https://github.com/RiziqStankovic/cls-test.git"
  #   path: "cls-log-test"
  #   targetRevision: "master"
    # releaseName: ""
  # - name: aws-baseline
  #   path: aws/etc-cluster-config
  #   namespace: aws-baseline
