argocdNamespace: argocd-tencent
project: xl-devops-platform-tencent-local
repoURL: https://github.com/RiziqStankovic/argocd-migration-sim.git
targetRevision: master
destinationServer: https://kubernetes.default.svc

applications:
  - name: tencent-cls-log-test
    path: tencent/prod/workload/cls-log-test
    namespace: tencent-dev
  - name: cls-log-test-awstencent
    path: tencent/cls-test
    namespace: tencent-nonprod
  # - name: aws-baseline
  #   path: aws/etc-cluster-config
  #   namespace: aws-baseline
